### ISSUE TITLE
Add Native github action support.

### ISSUE THREAD

**Issue by rjshrjndrn** [rjshrjndrn/templater#1]
Right now, I'm using following for embedding templater to github actions.

```yaml
    - name: Download templater
      run: |
        curl https://i.jpillora.com/rjshrjndrn/templater! | bash
```
